import officialRulesData from "./official-rules.generated.json";

const COMPREHENSIVE_RULES_URL = "https://en.palworld-official-cardgame.com/wordpress/wp-content/uploads/2026/07/30094316/%E3%80%90POCGe%E3%80%91Comprehensive-Rules_0729.pdf";
const OFFICIAL_QA_URL = "https://en.palworld-official-cardgame.com/question";

export type RuleAnswer = {
  id: string;
  question: string;
  answer: string;
  category: string;
  searchTerms: string[];
  sourceLabel: string;
  sourceUrl: string;
  updated: string;
  cardNumbers: string[];
  guideUrl?: string;
  featured: boolean;
  official: boolean;
};

const essentialRules: RuleAnswer[] = [
  {
    id: "deck-size",
    question: "How many cards are in a Palworld Card Game deck?",
    answer: "A legal deck uses exactly 50 Main Deck cards plus a separate Soul Deck of exactly 10 Soul cards.",
    category: "Deck Building",
    searchTerms: ["deck size", "how many cards", "50 cards", "10 souls", "main deck", "soul deck"],
    sourceLabel: "Comprehensive Rules 6.1",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-deck-building-rules",
    featured: true,
    official: false,
  },
  {
    id: "player-count",
    question: "How many players can play?",
    answer: "Palworld Official Card Game is designed for two players.",
    category: "Getting Started",
    searchTerms: ["player count", "two players", "2 player", "multiplayer"],
    sourceLabel: "Comprehensive Rules 1.1",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "win-condition",
    question: "How do you win or lose the game?",
    answer: "You win when your opponent loses. A player loses when their life reaches 0 or less, or when their Main Deck has no cards remaining. Simultaneous losses are a draw.",
    category: "Getting Started",
    searchTerms: ["win condition", "lose game", "victory", "zero life", "empty deck", "deck out"],
    sourceLabel: "Comprehensive Rules 1.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "starting-life",
    question: "How much life does each player start with?",
    answer: "Each player starts with 10 life.",
    category: "Game Setup",
    searchTerms: ["starting life", "life total", "health", "10 life"],
    sourceLabel: "Comprehensive Rules 6.2.1.8",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "opening-hand",
    question: "How many cards are in the opening hand?",
    answer: "Each player draws five cards from their Main Deck for their opening hand.",
    category: "Game Setup",
    searchTerms: ["starting hand", "opening hand size", "draw five", "5 cards"],
    sourceLabel: "Comprehensive Rules 6.2.1.6",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "mulligan",
    question: "How does a mulligan or redraw work?",
    answer: "Each player may redraw once during setup. Return all five cards to the Main Deck, shuffle, then draw five new cards. You cannot keep part of the hand.",
    category: "Game Setup",
    searchTerms: ["mulligan rules", "redraw hand", "replace cards", "opening hand"],
    sourceLabel: "Comprehensive Rules 6.2.1.7 and Official Q&A",
    sourceUrl: OFFICIAL_QA_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "second-player-soul",
    question: "Does the second player start with an extra Soul?",
    answer: "Yes. During setup, the player going second puts one card from their Soul Deck into their Soul Area.",
    category: "Game Setup",
    searchTerms: ["second player bonus", "starting soul", "extra soul", "going second"],
    sourceLabel: "Comprehensive Rules 6.2.1.5",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "first-player-draw",
    question: "Does the first player draw on the first turn?",
    answer: "No. The player going first skips the Draw Phase on the first turn and proceeds to the Soul Phase.",
    category: "Turn Flow",
    searchTerms: ["first player draw", "first turn draw", "skip draw", "going first"],
    sourceLabel: "Comprehensive Rules 7.3.1",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "attack-first-turn",
    question: "Can I attack on the first turn or with a Pal deployed this turn?",
    answer: "Yes. A standing Pal may attack even if it was deployed during that turn, unless an effect prevents it. The first-player exception is skipping the first Draw Phase, not an attack restriction.",
    category: "Battle",
    searchTerms: ["attack first turn", "summoning sickness", "new pal attack", "deployed this turn", "first player attack"],
    sourceLabel: "Comprehensive Rules 9.2.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "attack-targets",
    question: "What can a Pal attack?",
    answer: "A Pal can attack the opposing player, an opposing Structure, or an opposing Pal in the rest state. Assault allows a Pal to attack opposing Pals in the stand state.",
    category: "Battle",
    searchTerms: ["legal attack target", "allowed attack target", "what am I allowed to attack", "attack standing pal", "attack structure", "resting pal", "assault"],
    sourceLabel: "Comprehensive Rules 9.2.3 and 12.15",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "blocking",
    question: "How does blocking work?",
    answer: "When you are attacked, you may rest one eligible standing Pal you control. That Pal becomes the new attack target. A Stealth attack cannot be blocked.",
    category: "Battle",
    searchTerms: ["block attack", "defending pal", "change target", "stealth block"],
    sourceLabel: "Comprehensive Rules 9.4 and 12.11",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "pal-battle-damage",
    question: "What happens when one Pal attacks another Pal?",
    answer: "Both combat Pals deal damage equal to their Power to each other. A Pal is put into the Graveyard when its damage is equal to or greater than its current Power.",
    category: "Battle",
    searchTerms: ["pal combat", "battle damage", "destroy pal", "power damage graveyard"],
    sourceLabel: "Comprehensive Rules 9.6 and 11.4",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "structure-battle-damage",
    question: "Does a Structure deal damage back when attacked?",
    answer: "No. The attacking Pal deals damage equal to its Power to the Structure, but the Structure does not deal damage back.",
    category: "Battle",
    searchTerms: ["attack structure", "structure damage back", "durability combat"],
    sourceLabel: "Comprehensive Rules 9.6.3.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "damage-check",
    question: "How does player damage and a damage check work?",
    answer: "The attacker deals player damage equal to its Strike. Send that many cards from the top of the defending player's Main Deck to the Graveyard one at a time. If no Lucky icon appears, that player loses life equal to the full damage. If a Lucky icon appears, the check stops and that life loss is cancelled.",
    category: "Battle",
    searchTerms: ["damage check", "player damage", "strike", "mill cards", "lose life"],
    sourceLabel: "Comprehensive Rules 9.6 and 11.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "lucky-icon",
    question: "What does the Lucky icon do during damage?",
    answer: "When a Lucky-icon card goes from the top of the deck to the Graveyard during player damage resolution, the check stops and that damage's life loss is cancelled. The Lucky card and any cards already checked remain in the Graveyard.",
    category: "Battle",
    searchTerms: ["lucky pal", "lucky icon", "cancel damage", "damage check"],
    sourceLabel: "Comprehensive Rules 11.2.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/how-to-play-palworld-card-game",
    featured: true,
    official: false,
  },
  {
    id: "deck-colors",
    question: "How many colors can a deck use?",
    answer: "A Main Deck may use up to two of Red, Blue, Green and Purple. Colorless cards can be included alongside those colors.",
    category: "Deck Building",
    searchTerms: ["two color rule", "deck colors", "colour limit", "colorless cards"],
    sourceLabel: "Official Quick Manual",
    sourceUrl: "https://en.palworld-official-cardgame.com/wordpress/wp-content/uploads/2026/06/26104921/Palworld-OFFICIAL-CARD-GAME-Play-Guide_EN.pdf",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-deck-building-rules",
    featured: true,
    official: false,
  },
  {
    id: "copy-limit",
    question: "How many copies of the same card can I use?",
    answer: "You may include no more than four cards with the same full card name in the Main Deck.",
    category: "Deck Building",
    searchTerms: ["four copy rule", "4 copies", "same name limit", "duplicate cards"],
    sourceLabel: "Comprehensive Rules 6.1.1.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-deck-building-rules",
    featured: true,
    official: false,
  },
  {
    id: "lucky-deck-limit",
    question: "How many Lucky-icon cards can a deck contain?",
    answer: "A Main Deck may include up to eight cards with the Lucky Pal icon. The normal four-copy rule still applies.",
    category: "Deck Building",
    searchTerms: ["lucky card limit", "eight lucky", "8 lucky cards", "deck construction"],
    sourceLabel: "Comprehensive Rules 6.1.1.3",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-deck-building-rules",
    featured: true,
    official: false,
  },
  {
    id: "quick",
    question: "What does Quick mean?",
    answer: "Quick cards and abilities may be used during the battle Quick Step. On your own Main Phase, a Quick card can also be played at normal legal timing.",
    category: "Keywords",
    searchTerms: ["quick timing", "play on opponent turn", "response card", "quick step"],
    sourceLabel: "Comprehensive Rules 9.5 and 12.2",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-keyword-glossary",
    featured: true,
    official: false,
  },
  {
    id: "interrupt",
    question: "What does Interrupt do?",
    answer: "Interrupt is a Quick ability used from the hand. Pay its listed cost to nullify the opponent's attack, which moves the battle directly to the end-of-battle step.",
    category: "Keywords",
    searchTerms: ["interrupt timing", "cancel attack", "nullify battle", "discard from hand"],
    sourceLabel: "Comprehensive Rules 5.18 and 12.8",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-keyword-glossary",
    featured: true,
    official: false,
  },
  {
    id: "taunt",
    question: "How does Taunt work?",
    answer: "If a card with Taunt can legally be attacked, the opponent must choose a Taunt card as the attack target. If several are legal, the attacker chooses among them.",
    category: "Keywords",
    searchTerms: ["taunt target", "must attack", "multiple taunt"],
    sourceLabel: "Comprehensive Rules 12.10",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-keyword-glossary",
    featured: true,
    official: false,
  },
  {
    id: "stealth",
    question: "What does Stealth mean?",
    answer: "Stealth means that attacks made by that card cannot be blocked.",
    category: "Keywords",
    searchTerms: ["stealth attack", "cannot block", "unblockable"],
    sourceLabel: "Comprehensive Rules 12.11",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-keyword-glossary",
    featured: true,
    official: false,
  },
  {
    id: "assault",
    question: "What does Assault mean?",
    answer: "Assault allows a Pal to choose an opposing Pal in the stand state as its attack target.",
    category: "Keywords",
    searchTerms: ["assault keyword", "attack standing pal"],
    sourceLabel: "Comprehensive Rules 12.15",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-keyword-glossary",
    featured: true,
    official: false,
  },
  {
    id: "soul-draw",
    question: "Can I rest three Souls to draw a card?",
    answer: "Yes. During your Main Phase, you may pay three Souls to draw one card. This action can be used only once per turn.",
    category: "Turn Flow",
    searchTerms: ["three souls draw", "3 souls", "extra draw", "once per turn"],
    sourceLabel: "Comprehensive Rules 8.5",
    sourceUrl: COMPREHENSIVE_RULES_URL,
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "first-purchase",
    question: "What should a new player buy first?",
    answer: "Start with either Trial Deck because it contains a complete 50-card Main Deck, 10-card Soul Deck, counters, a paper playmat and guide. Buy boosters later for collecting and upgrades.",
    category: "Products",
    searchTerms: ["what should I buy", "best first purchase", "new player product", "starter deck", "trial deck"],
    sourceLabel: "Official beginner and product pages",
    sourceUrl: "https://en.palworld-official-cardgame.com/for-beginners",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-products-where-to-buy",
    featured: true,
    official: false,
  },
  {
    id: "where-to-buy",
    question: "Where can I buy Palworld Card Game products?",
    answer: "Use Bushiroad's official retailer finder first, then confirm the product code and language before buying.",
    category: "Products",
    searchTerms: ["where to buy", "shop cards", "retailer", "local store", "purchase"],
    sourceLabel: "Official retailer finder",
    sourceUrl: "https://www.en.bushi-navi.com/storelist?default=true",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-products-where-to-buy",
    featured: true,
    official: false,
  },
  {
    id: "booster-only",
    question: "Can I start playing with only a booster pack?",
    answer: "No. A booster pack does not contain the exact 50-card Main Deck and 10-card Soul Deck needed to play. Start with a Trial Deck.",
    category: "Products",
    searchTerms: ["booster pack enough", "play from packs", "complete deck", "start playing"],
    sourceLabel: "Official beginner page",
    sourceUrl: "https://en.palworld-official-cardgame.com/for-beginners",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/palworld-card-game-products-where-to-buy",
    featured: true,
    official: false,
  },
  {
    id: "best-deck",
    question: "What is the best deck or launch-day tier list?",
    answer: "There is no reliable tournament meta yet. The two official Trial Decks are the only fixed complete lists at launch; treat other decks as testing ideas until verified event results exist.",
    category: "Decks",
    searchTerms: ["best deck", "meta deck", "tier list", "top deck", "winning list"],
    sourceLabel: "Editorial status based on available results",
    sourceUrl: "/decks",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/decks",
    featured: true,
    official: false,
  },
  {
    id: "pull-rates",
    question: "What are the Dawn of Palpagos pull rates?",
    answer: "Bushiroad confirms 100 base card types and 61 parallel types, but has not published complete per-rarity pull odds. Early box openings are not enough to claim reliable rates.",
    category: "Collecting",
    searchTerms: ["pull rates", "box odds", "hit rate", "rarity odds", "case ratio"],
    sourceLabel: "Official BP01 product page",
    sourceUrl: "https://en.palworld-official-cardgame.com/products/bp01",
    updated: "2026/07/30",
    cardNumbers: [],
    guideUrl: "/blog/dawn-of-palpagos-pull-rates",
    featured: true,
    official: false,
  },
  {
    id: "release-tournament",
    question: "When are the Grand Release Tournaments?",
    answer: "Official tournament stores may hold one Grand Release Tournament between August 1 and August 31, 2026. Check the official event page and Bushi Navi for participating stores.",
    category: "Events",
    searchTerms: ["release tournament", "launch event", "local event", "organized play", "august tournament"],
    sourceLabel: "Official Grand Release Tournament page",
    sourceUrl: "https://en.palworld-official-cardgame.com/events/grand-release-tournament",
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
  {
    id: "next-products",
    question: "What Palworld Card Game products come after launch?",
    answer: "The official product list shows Sleeve & Card Set Vol. 1 for October 2, 2026 and the Legends Awaken booster for October 30, 2026.",
    category: "Products",
    searchTerms: ["next set", "future set", "legends awaken", "release schedule", "October products"],
    sourceLabel: "Official product list",
    sourceUrl: "https://en.palworld-official-cardgame.com/products",
    updated: "2026/07/30",
    cardNumbers: [],
    featured: true,
    official: false,
  },
];

type OfficialRuleRecord = {
  id: string;
  question: string;
  answer: string;
  category: string;
  cardNumbers: string[];
  cardNames: string;
  updated: string;
  sourceUrl: string;
};

const officialRules = (officialRulesData.rules as OfficialRuleRecord[]).map<RuleAnswer>((rule) => ({
  id: rule.id,
  question: rule.question,
  answer: rule.answer,
  category: rule.category,
  searchTerms: [...rule.cardNumbers, rule.cardNames],
  sourceLabel: "Official Rule Q&A",
  sourceUrl: rule.sourceUrl,
  updated: rule.updated,
  cardNumbers: rule.cardNumbers,
  featured: false,
  official: true,
}));

export const ruleAnswers = [...essentialRules, ...officialRules];
export const featuredRuleAnswers = essentialRules;
export const officialRuleCount = officialRules.length;
export const ruleCategories = ["All", ...new Set(ruleAnswers.map((rule) => rule.category))];
